<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>0649</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Integration/NPCs/Goblin/GoblinNPC.cs" />
    <Compile Include="../../../Integration/NPCs/Goblin/GoblinNPCRuntimeModuleHostBridge.cs" />
    <Compile Include="Stubs.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
