<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion><EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="../../../DebugAndTools/SkyIsland/SkyIslandLighting.cs" />
    <Compile Include="../../../DebugAndTools/SkyIsland/SkyIslandNight.cs" />
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManagedPath)/UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime"><HintPath>$(GameManagedPath)/Unity.RenderPipelines.Core.Runtime.dll</HintPath></Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime"><HintPath>$(GameManagedPath)/Unity.RenderPipelines.Universal.Runtime.dll</HintPath></Reference>
    <Reference Include="TeamSoda.Duckov.Core"><HintPath>$(GameManagedPath)/TeamSoda.Duckov.Core.dll</HintPath></Reference>
  </ItemGroup>
</Project>
