<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Integration/Dialogue/DialogueManager.cs" Link="DialogueManager.cs" />
    <Compile Include="../../../DebugAndTools/SkyIsland/SkyIslandResidentDialogue.cs" Link="SkyIslandResidentDialogue.cs" />
  </ItemGroup>
</Project>
