<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion><EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>0649</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Common/Buildings/BuildingInjectionHelper.cs" />
    <Compile Include="../../../Integration/ContentBuildingBridges.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
