<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <LangVersion>7.3</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Stubs.cs" />
    <Compile Include="../../../Integration/NewWeapons/EmptyMagazineMine/EmptyMagazineMineRules.cs" />
    <Compile Include="../../../Integration/NewWeapons/EmptyMagazineMine/EmptyMagazineMineRuntime.cs" />
    <Compile Include="../../../Integration/NewWeapons/EmptyMagazineMine/EmptyMagazineMineConfig.cs" />
    <Compile Include="../../../Config/ConfigItemIds.cs" />
  </ItemGroup>
</Project>
