<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)../../../Build/content-third-review-fixes/$(MSBuildProjectName)/obj/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)../../../Build/content-third-review-fixes/$(MSBuildProjectName)/bin/</BaseOutputPath>
  </PropertyGroup>
</Project>
